# Generated by Django 2.0.7 on 2018-07-11 11:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrySentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='title')),
                ('pronunciation', models.CharField(max_length=250, verbose_name='pronunciation')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'entry sentence',
                'verbose_name_plural': 'entry sentences',
            },
        ),
        migrations.CreateModel(
            name='EntrySentenceCompound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='position')),
                ('from_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_entry_sentence', to='voca.EntrySentence')),
                ('to_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_entry_sentence', to='voca.Entry')),
            ],
            options={
                'verbose_name': 'compound word',
                'verbose_name_plural': 'compound words',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='entrysentence',
            name='relationships',
            field=models.ManyToManyField(blank=True, related_name='components', through='voca.EntrySentenceCompound', to='voca.EntrySentence'),
        ),
    ]
