# Generated by Django 2.0.7 on 2018-07-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='relationships',
            field=models.ManyToManyField(blank=True, related_name='components', through='voca.EntryCompound', to='voca.Entry'),
        ),
    ]
