# Generated by Django 2.0.7 on 2018-07-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='relationships',
        ),
        migrations.AddField(
            model_name='entry',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='entries', through='voca.EntryCompound', to='voca.Entry'),
        ),
    ]
