# Generated by Django 2.0.7 on 2018-07-05 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrymeaning',
            old_name='meaning',
            new_name='entry',
        ),
    ]
