# Generated by Django 2.0.7 on 2018-07-11 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrysentencecompound',
            options={'ordering': ['position'], 'verbose_name': 'word', 'verbose_name_plural': 'words'},
        ),
    ]
