# Generated by Django 2.0.7 on 2018-07-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrycategorymembership',
            options={'ordering': ['position'], 'verbose_name': 'category membership', 'verbose_name_plural': 'category memberships'},
        ),
        migrations.AddField(
            model_name='entrycategorymembership',
            name='position',
            field=models.IntegerField(default=1, verbose_name='position'),
            preserve_default=False,
        ),
    ]
