# Generated by Django 2.0.7 on 2018-07-05 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'entry', 'verbose_name_plural': 'entries'},
        ),
        migrations.AlterModelOptions(
            name='entrycompound',
            options={'ordering': ['position'], 'verbose_name': 'compound word', 'verbose_name_plural': 'compound words'},
        ),
        migrations.AlterModelOptions(
            name='entrymeaning',
            options={'verbose_name': 'meaning', 'verbose_name_plural': 'meanings'},
        ),
        migrations.AddField(
            model_name='entrymeaning',
            name='position',
            field=models.IntegerField(default=1, verbose_name='position'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrycompound',
            name='from_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='어근', to='voca.Entry'),
        ),
        migrations.AlterField(
            model_name='entrycompound',
            name='to_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='파생어', to='voca.Entry'),
        ),
    ]
