# Generated by Django 2.0.7 on 2018-07-09 16:23

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='표제어', to='voca.EntryCategory', verbose_name='entry category'),
        ),
    ]
