# Generated by Django 2.0.7 on 2018-07-17 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrytextbookcompound',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voca.Entry', verbose_name='entry'),
        ),
        migrations.AlterField(
            model_name='entrytextbookcompound',
            name='textbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voca.Textbook', verbose_name='textbook'),
        ),
    ]
