# Generated by Django 2.0.7 on 2018-07-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.SlugField(allow_unicode=True, max_length=255, verbose_name='title'),
        ),
    ]
