# Generated by Django 2.0.7 on 2018-07-12 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrySentenceCompound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='position')),
                ('from_sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voca.EntrySentence')),
                ('to_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voca.Entry')),
            ],
            options={
                'verbose_name': 'word',
                'verbose_name_plural': 'words',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='entrysentence',
            name='words',
            field=models.ManyToManyField(blank=True, through='voca.EntrySentenceCompound', to='voca.Entry'),
        ),
    ]
