# Generated by Django 2.0.7 on 2018-07-11 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrymeaning',
            options={'ordering': ['position'], 'verbose_name': 'meaning', 'verbose_name_plural': 'meanings'},
        ),
    ]
