# Generated by Django 2.0.7 on 2018-07-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0002_auto_20180706_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='title',
            new_name='slug',
        ),
    ]
