# Generated by Django 2.0.7 on 2018-07-07 15:09

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0002_auto_20180707_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='category',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='표제어', to='voca.EntryCategory', verbose_name='entry category'),
        ),
    ]
