# Generated by Django 2.0.7 on 2018-07-11 12:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0002_auto_20180711_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrysentencecompound',
            name='from_entry',
        ),
        migrations.AddField(
            model_name='entrysentencecompound',
            name='from_sentence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='from_sentence', to='voca.EntrySentence'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrysentencecompound',
            name='to_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='단어', to='voca.Entry'),
        ),
    ]
