# Generated by Django 2.0.7 on 2018-07-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0002_auto_20180707_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='slug',
            new_name='title',
        ),
    ]
