# Generated by Django 2.0.7 on 2018-07-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0002_auto_20180712_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrysentence',
            name='words',
            field=models.ManyToManyField(blank=True, through='voca.EntrySentenceCompound', to='voca.Entry'),
        ),
    ]
