# Generated by Django 2.0.7 on 2018-07-12 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0002_auto_20180712_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrycompound',
            name='to_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_entry', to='voca.Entry', verbose_name='compound word'),
        ),
    ]
