# Generated by Django 2.0.7 on 2018-07-12 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0002_auto_20180712_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrysentence',
            old_name='relationships',
            new_name='words',
        ),
    ]
