# Generated by Django 2.0.7 on 2018-07-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0002_auto_20180705_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrymeaning',
            name='meaning',
            field=models.CharField(default='', max_length=250, verbose_name='meaning'),
            preserve_default=False,
        ),
    ]
