# Generated by Django 2.0.7 on 2018-07-15 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0002_textbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryTextbookCompound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField(verbose_name='chapter')),
                ('page', models.IntegerField(verbose_name='page')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voca.Entry')),
            ],
            options={
                'verbose_name': 'textbook word',
                'verbose_name_plural': 'textbook words',
                'ordering': ['chapter', 'page'],
            },
        ),
        migrations.AlterModelOptions(
            name='textbook',
            options={'ordering': ['position'], 'verbose_name': 'textbook', 'verbose_name_plural': 'textbooks'},
        ),
        migrations.AddField(
            model_name='textbook',
            name='position',
            field=models.IntegerField(default=1, verbose_name='position'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrytextbookcompound',
            name='textbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voca.Textbook'),
        ),
    ]
