# Generated by Django 2.0.7 on 2018-07-11 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0002_auto_20180711_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrycompound',
            options={'ordering': ('position',), 'verbose_name': 'compound word', 'verbose_name_plural': 'compound words'},
        ),
    ]
