# Generated by Django 2.0.7 on 2018-07-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0003_auto_20180712_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrysentencecompound',
            name='from_sentence',
        ),
        migrations.RemoveField(
            model_name='entrysentencecompound',
            name='to_entry',
        ),
        migrations.RemoveField(
            model_name='entrysentence',
            name='words',
        ),
        migrations.DeleteModel(
            name='EntrySentenceCompound',
        ),
    ]
