# Generated by Django 2.0.7 on 2018-07-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0003_auto_20180715_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='words',
            field=models.ManyToManyField(blank=True, through='voca.EntryTextbookCompound', to='voca.Entry'),
        ),
    ]
