# Generated by Django 2.0.7 on 2018-07-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0003_auto_20180712_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrysentence',
            name='relationships',
            field=models.ManyToManyField(blank=True, related_name='sentences', through='voca.EntrySentenceCompound', to='voca.EntrySentence'),
        ),
    ]
