# Generated by Django 2.0.7 on 2018-07-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0003_auto_20180707_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='title'),
        ),
    ]
