# Generated by Django 2.0.7 on 2018-07-12 01:42

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0003_auto_20180712_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voca.EntryCategory', verbose_name='entry category'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='components',
            field=models.ManyToManyField(blank=True, through='voca.EntryCompound', to='voca.Entry'),
        ),
        migrations.AlterField(
            model_name='entrycompound',
            name='from_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_entry', to='voca.Entry'),
        ),
        migrations.AlterField(
            model_name='entrycompound',
            name='to_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_entry', to='voca.Entry'),
        ),
        migrations.AlterField(
            model_name='entrymeaning',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voca.Entry', verbose_name='entry'),
        ),
        migrations.AlterField(
            model_name='entrysentence',
            name='words',
            field=models.ManyToManyField(blank=True, through='voca.EntrySentenceCompound', to='voca.EntrySentence'),
        ),
        migrations.AlterField(
            model_name='entrysentencecompound',
            name='from_sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voca.EntrySentence'),
        ),
        migrations.AlterField(
            model_name='entrysentencecompound',
            name='to_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voca.Entry'),
        ),
    ]
