# Generated by Django 2.0.7 on 2018-07-12 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0004_auto_20180712_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrymeaning',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='voca.Entry', verbose_name='entry'),
        ),
    ]
