# Generated by Django 2.0.7 on 2018-07-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0004_textbook_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='chapter',
            field=models.IntegerField(default=1, verbose_name='chapter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrytextbookcompound',
            name='page',
            field=models.IntegerField(blank=True, null=True, verbose_name='page'),
        ),
    ]
