# Generated by Django 2.0.7 on 2018-07-11 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0004_auto_20180712_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrysentencecompound',
            name='to_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_sentence_entry', to='voca.Entry'),
        ),
    ]
