# Generated by Django 2.0.7 on 2018-07-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0005_auto_20180712_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrysentence',
            name='description',
        ),
        migrations.AddField(
            model_name='entrysentence',
            name='meaning',
            field=models.TextField(blank=True, verbose_name='meaning'),
        ),
    ]
