# Generated by Django 2.0.7 on 2018-07-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_noticemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticemessage',
            name='markup',
            field=models.IntegerField(choices=[(0, 'html'), (1, 'markdown'), (2, 'text')], default=0, verbose_name='markup'),
        ),
    ]
