# Generated by Django 2.0.7 on 2018-07-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.CharField(default='test@example.com', max_length=254, verbose_name='email'),
            preserve_default=False,
        ),
    ]
