# Generated by Django 2.0.7 on 2018-07-15 16:48

import book.models
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content1',
            field=models.TextField(blank=True, verbose_name='content1'),
        ),
        migrations.AddField(
            model_name='page',
            name='content2',
            field=models.TextField(blank=True, verbose_name='content2'),
        ),
        migrations.AddField(
            model_name='page',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=book.models.upload_directory_path, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='page',
            name='youtube',
            field=models.URLField(blank=True, verbose_name='youtube'),
        ),
    ]
