# Generated by Django 2.0.7 on 2018-07-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['position', '-created'], 'verbose_name': 'book', 'verbose_name_plural': 'books'},
        ),
        migrations.AddField(
            model_name='book',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='position'),
        ),
    ]
