# Generated by Django 2.0.7 on 2018-07-24 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0001_initial'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryArticleMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='position')),
                ('from_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Article')),
                ('to_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voca.Entry')),
            ],
            options={
                'verbose_name': 'word',
                'verbose_name_plural': 'words',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='words',
            field=models.ManyToManyField(blank=True, through='book.EntryArticleMembership', to='voca.Entry'),
        ),
    ]
