# Generated by Django 2.0.7 on 2018-07-05 14:18

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Site menu item title. Can contain template variables E.g.: {{ mytitle }}', max_length=255, verbose_name='title')),
                ('url', models.CharField(db_index=True, help_text='Exact URL or URL pattern', max_length=255, verbose_name='url')),
                ('match', models.IntegerField(choices=[(0, 'equals'), (1, 'startswith')], default=0, verbose_name='match')),
                ('target', models.IntegerField(choices=[(0, '_self'), (1, 'blank')], default=0, verbose_name='target')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='rakmai.MenuItem', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'menu item',
                'verbose_name_plural': 'menu items',
                'ordering': ['tree_id', 'lft'],
            },
        ),
    ]
